version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      # - run:
      #     name: Run tests
      #     command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_test
